---
#run with
# ansible-playbook -i hosts elk-rpi.yml
- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - vars/vars-rpi.yml
  roles:
    - { role: common-rpi }
    - { role: java-rpi }
    - { role: elasticsearch-rpi }
    # - { role: logstash-rpi }
    # - { role: kibana-rpi }

