# ---
# - block:
#   - name: Install | download deb file
#     geturl:
#       url: {{ elasticsearch_deb_url }}
#       dest: /home/pi
#       force: no
#     when: install_type == "download-oracle"  or install_type == "openjdk"
#     register: download_deb
  
#   - name: Install | install deb file
#     apt:
#       deb: /home/pi/{{ elasticsearch_deb_filename }}
#     when: install_type == "download-oracle" or install_type == "openjdk"

#   - name: Config | jvm heap size min
#     lineinfile:
#       dest: /etc/elasticsearch/jvm.options
#       regexp: '^-Xms500m'
#       state: present
#       line: -Xms256m
#   - name: Start elastisearch service
#     service:
#       name: elastisearch
#       state: started
#       enabled: yes

#   tags:
#     - install
#     - elasticsearch